image: atlassian/default-image:3

pipelines:
  branches:
    sugon-pr/*:
      - step:
          clone:
            depth: full
          script:
            - git push https://${GH_TOKEN}@github.com/${GH_USER}/aomp.git ${BITBUCKET_BRANCH}
